name: Build Docker Images

on:
  push:
    tags:
      - '*'

jobs:
  build-graphql:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file Naami.Distributor.GraphQL/Dockerfile --tag naamitest/dew-graphql:$RELEASE_VERSION
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: naamitest
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - name: Publish Docker Image
      run: docker push naamitest/dew-graphql:$RELEASE_VERSION
